# Generated by Django 4.2 on 2024-01-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Footer data', 'verbose_name_plural': 'Footer data'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Home carusel', 'verbose_name_plural': 'Home carusel'},
        ),
        migrations.AlterModelOptions(
            name='homecontent',
            options={'verbose_name': 'Home content', 'verbose_name_plural': 'Home content'},
        ),
        migrations.AlterModelOptions(
            name='why',
            options={'verbose_name': 'Why', 'verbose_name_plural': 'Why'},
        ),
        migrations.AlterField(
            model_name='home',
            name='home_disc',
            field=models.CharField(max_length=50),
        ),
    ]
