# Generated by Django 4.2 on 2024-01-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_footer_options_alter_home_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.RemoveField(
            model_name='why',
            name='img',
        ),
        migrations.AddField(
            model_name='why',
            name='icon',
            field=models.CharField(choices=[('gantel', 'Гантель'), ('banka', 'Банка'), ('bike', 'Велик'), ('timer', 'Таймер')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footer',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='img',
            field=models.ImageField(blank=True, default='/static/images/defoult-avatar-icon', null=True, upload_to='images/trainer'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
