# Generated by Django 4.2 on 2024-01-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_home_disc_home_disc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='disc',
            field=models.CharField(max_length=255),
        ),
    ]
